apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases
patches:
  - path: patch-image.yaml
    target:
      group: apis.clusterfleet.io
      version: v1alpha1
      kind: Application
      name: automq-controller-init-rongyu
